import { ColumnMenu } from "./columnMenu";

const columns = [
  {
    title: "Emp ID",
    field: "empId",
    show: true,
    filter: "text",
    locked: true,
    width: "80px",
  },
  {
    title: "First Name",
    field: "firstName",
    show: true,
    filter: "text",
    locked: true,
    width: "200px",
  },
  {
    title: "Last Name",
    field: "lastName",
    show: true,
    filter: "text",
    locked: true,
    width: "200px",
  },
  {
    title: "Work Phone",
    field: "workPhone",
    show: true,
    locked: false,
    filter: "text",
    width: "200px",
  },
  {
    title: "Home Phone",
    field: "homePhone",
    show: true,
    locked: false,
    filter: "text",
    width: "200px",
  },
  {
    title: "Title",
    locked: false,
    field: "title",
    show: true,
    filter: "text",
    width: "200px",
  },
  {
    title: "Email",
    field: "email",
    locked: false,
    show: true,
    filter: "text",
    width: "200px",
  },
  {
    field: "supervisor",
    title: "Supervisor",
    locked: false,
    show: true,
    filter: "text",
    width: "200px",
  },
  {
    field: "cellPhone",
    title: "Cell Phone",
    width: "200px",
    locked: false,
    show: true,
    filter: "text",
  },
  {
    field: "enabledFlag",
    title: "Enabled Flag",
    width: "200px",
    filter: "boolean",
    locked: false,
    show: true,
  },
];

export default columns;
